
###localhost

GET http://localhost:3000/api/persons

###
DELETE http://localhost:3000/api/persons/2


###

POST http://localhost:3000/api/persons  HTTP/1.1
Content-Type:application/json

{
    "name": "sde",
    "number": "12345678"
  }

### Heroku server

GET https://calm-bastion-54373.herokuapp.com/api/persons

###
DELETE https://calm-bastion-54373.herokuapp.com/api/persons/2


###
POST https://calm-bastion-54373.herokuapp.com/api/persons  HTTP/1.1
Content-Type:application/json

{
    "name": "sdsadasdsde",
    "number": "12345678"
  }
